### ISSUE TITLE
Djmally

### ISSUE THREAD

**Issue by feefles** [STWing/Bylaws#10]
dj mally is a dj

**Comment by djmally** [comment]
@feefles this is not appropriate use of our issue tracker, I am revoking your access to this repository and putting you on probation for a period of one (1) month(s). Please contact the STWing Continuum at continuum@lists.stwing.upenn.edu for more information about this ban.

:+1: :100: :steam_locomotive: :8ball: :hamburger: :pager: :santa: :last_quarter_moon_with_face: :new_moon_with_face:

**Comment by feefles** [comment]
~~you don't need access to the repo to open issues.~~
hi my name is fifi i like trains :steam_locomotive: :train: :train2: :bullettrain_side: :bullettrain_front: #choochoo
