### ISSUE TITLE
Add one month to winter-elected Continuum positions

### ISSUE THREAD

**Issue by kainino0x** [STWing/Bylaws#7]
Amend the bylaws to:
* add one month to winter-elected Continuum positions' terms

**Comment by kainino0x** [comment]
This has been voted and accepted by the General Body.

**Comment by djmally** [comment]
Bylaw text:
Bylaw Amendment Proposals: October, 2015
Proposal 1: Extended Term Length
Bylaw 4.3
The elected Members of the Continuum shall be determined by an election to be held at the first general body meeting of the second semester of each academic year, where the term of election shall be one calendar year and one month with no term limits. The outgoing Continuum members shall overlap with the incoming Continuum members for the period of one month, during which all responsibilities will be transferred to the incoming Continuum. The outgoing Continuum is strongly encouraged to attend Continuum meetings for an additional month to advise the new members. However, the following Continuum positions shall be elected at the first general body meeting of the fall semester: Wall-E, Ada, Samwise, Frodo, and Gandalf. The term of election on these positions shall be one calendar year from the time of election.

**Comment by djmally** [comment]
Resolved in #9
